In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math as math
frame = pd.read_csv('/content/Mcdonalds.csv', usecols=['Item', 'Category', 'Serving Size', 'Calories', 'TotalFat'])
frame.head()

    Category                              Item  ... Calories  TotalFat
0  Breakfast                      Egg McMuffin  ...      300      13.0
1  Breakfast                 Egg White Delight  ...      250       8.0
2  Breakfast                  Sausage McMuffin  ...      370      23.0
3  Breakfast         Sausage McMuffin with Egg  ...      450      28.0
4  Breakfast  Sausage McMuffin with Egg Whites  ...      400      23.0

[5 rows x 5 columns]

In [ ]:
 frame.sort_values(by='Calories').head()

         Category                    Item  Serving Size  Calories  TotalFat
125     Beverages  Diet Dr Pepper (Child)  12 fl oz cup         0       0.0
138  Coffee & Tea       Iced Tea (Medium)  21 fl oz cup         0       0.0
137  Coffee & Tea        Iced Tea (Small)  16 fl oz cup         0       0.0
136     Beverages     Dasani Water Bottle    16.9 fl oz         0       0.0
145  Coffee & Tea          Coffee (Small)  12 fl oz cup         0       0.0

In [ ]:
frame.sort_values(by='Calories', ascending=False).head()

          Category  ... TotalFat
82  Chicken & Fish  ...    118.0
32       Breakfast  ...     60.0
31       Breakfast  ...     56.0
34       Breakfast  ...     50.0
33       Breakfast  ...     46.0

[5 rows x 5 columns]

Aby zabrudzić dane muszę najpierw przekonwertować wartości typu int do wartości typu float

In [ ]:
frame['Calories'] = frame['Calories'].astype('float')
frame.loc[82, 'Calories'] = np.NaN
frame.head()

    Category                              Item  ... Calories  TotalFat
0  Breakfast                      Egg McMuffin  ...    300.0      13.0
1  Breakfast                 Egg White Delight  ...    250.0       8.0
2  Breakfast                  Sausage McMuffin  ...    370.0      23.0
3  Breakfast         Sausage McMuffin with Egg  ...    450.0      28.0
4  Breakfast  Sausage McMuffin with Egg Whites  ...    400.0      23.0

[5 rows x 5 columns]

In [ ]:
frame.loc[82]

Category                      Chicken & Fish
Item            Chicken McNuggets (40 piece)
Serving Size                 22.8 oz (646 g)
Calories                                 NaN
TotalFat                                 118
Name: 82, dtype: object

Wartość NaN jest uważana za największą w kolumnie Calories

In [ ]:
frame.sort_values(by='Calories').tail()

          Category  ... TotalFat
33       Breakfast  ...     46.0
34       Breakfast  ...     50.0
31       Breakfast  ...     56.0
32       Breakfast  ...     60.0
82  Chicken & Fish  ...    118.0

[5 rows x 5 columns]

Posortowanie NaN od góry dzięki na_position

In [ ]:
frame.sort_values(by='Calories',na_position='first').head()

           Category                          Item  ... Calories  TotalFat
82   Chicken & Fish  Chicken McNuggets (40 piece)  ...      NaN     118.0
114       Beverages             Diet Coke (Small)  ...      0.0       0.0
139    Coffee & Tea              Iced Tea (Large)  ...      0.0       0.0
138    Coffee & Tea             Iced Tea (Medium)  ...      0.0       0.0
137    Coffee & Tea              Iced Tea (Small)  ...      0.0       0.0

[5 rows x 5 columns]

In [ ]:
frame.sort_values(by=['Category', 'Item']).head(20)

        Category                                       Item  ... Calories  TotalFat
51   Beef & Pork                     Bacon Clubhouse Burger  ...    720.0      40.0
53   Beef & Pork                             Bacon McDouble  ...    440.0      22.0
42   Beef & Pork                                    Big Mac  ...    530.0      27.0
49   Beef & Pork                               Cheeseburger  ...    290.0      11.0
54   Beef & Pork                               Daily Double  ...    430.0      22.0
50   Beef & Pork                        Double Cheeseburger  ...    430.0      21.0
47   Beef & Pork         Double Quarter Pounder with Cheese  ...    750.0      43.0
48   Beef & Pork                                  Hamburger  ...    240.0       8.0
55   Beef & Pork                            Jalapeño Double  ...    430.0      23.0
52   Beef & Pork                                   McDouble  ...    380.0      17.0
56   Beef & Pork                                      McRib  ...    500.0      26.0
46   Beef & Pork                     Quarter Pounder Deluxe  ...    540.0      27.0
44   Beef & Pork        Quarter Pounder with Bacon & Cheese  ...    600.0      29.0
45   Beef & Pork  Quarter Pounder with Bacon Habanero Ranch  ...    610.0      31.0
43   Beef & Pork                Quarter Pounder with Cheese  ...    520.0      26.0
130    Beverages                        1% Low Fat Milk Jug  ...    100.0       2.5
113    Beverages                  Coca-Cola Classic (Child)  ...    100.0       0.0
112    Beverages                  Coca-Cola Classic (Large)  ...    280.0       0.0
111    Beverages                 Coca-Cola Classic (Medium)  ...    200.0       0.0
110    Beverages                  Coca-Cola Classic (Small)  ...    140.0       0.0

[20 rows x 5 columns]

In [ ]:
frame.sort_values(by=['Category', 'Item'], ascending=[True,False]).head(20)

        Category                                       Item  ... Calories  TotalFat
43   Beef & Pork                Quarter Pounder with Cheese  ...    520.0      26.0
45   Beef & Pork  Quarter Pounder with Bacon Habanero Ranch  ...    610.0      31.0
44   Beef & Pork        Quarter Pounder with Bacon & Cheese  ...    600.0      29.0
46   Beef & Pork                     Quarter Pounder Deluxe  ...    540.0      27.0
56   Beef & Pork                                      McRib  ...    500.0      26.0
52   Beef & Pork                                   McDouble  ...    380.0      17.0
55   Beef & Pork                            Jalapeño Double  ...    430.0      23.0
48   Beef & Pork                                  Hamburger  ...    240.0       8.0
47   Beef & Pork         Double Quarter Pounder with Cheese  ...    750.0      43.0
50   Beef & Pork                        Double Cheeseburger  ...    430.0      21.0
54   Beef & Pork                               Daily Double  ...    430.0      22.0
49   Beef & Pork                               Cheeseburger  ...    290.0      11.0
42   Beef & Pork                                    Big Mac  ...    530.0      27.0
53   Beef & Pork                             Bacon McDouble  ...    440.0      22.0
51   Beef & Pork                     Bacon Clubhouse Burger  ...    720.0      40.0
126    Beverages                             Sprite (Small)  ...    140.0       0.0
127    Beverages                            Sprite (Medium)  ...    200.0       0.0
128    Beverages                             Sprite (Large)  ...    280.0       0.0
129    Beverages                             Sprite (Child)  ...    100.0       0.0
133    Beverages           Minute Maid Orange Juice (Small)  ...    150.0       0.0

[20 rows x 5 columns]

Sortowanie po indeksie

In [ ]:
frame = pd.read_csv('/content/Mcdonalds.csv', usecols=['Item', 'Category', 'Serving Size', 'Calories', 'TotalFat'],index_col='Item')
frame.head()

                                   Category    Serving Size  Calories  TotalFat
Item
Egg McMuffin                      Breakfast  4.8 oz (136 g)       300      13.0
Egg White Delight                 Breakfast  4.8 oz (135 g)       250       8.0
Sausage McMuffin                  Breakfast  3.9 oz (111 g)       370      23.0
Sausage McMuffin with Egg         Breakfast  5.7 oz (161 g)       450      28.0
Sausage McMuffin with Egg Whites  Breakfast  5.7 oz (161 g)       400      23.0

In [ ]:
frame.sort_index(ascending=True).head()

                                     Category  ... TotalFat
Item                                           ...
1% Low Fat Milk Jug                 Beverages  ...      2.5
Apple Slices                   Snacks & Sides  ...      0.0
Bacon Buffalo Ranch McChicken  Chicken & Fish  ...     21.0
Bacon Cheddar McChicken        Chicken & Fish  ...     24.0
Bacon Clubhouse Burger            Beef & Pork  ...     40.0

[5 rows x 4 columns]