In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math as math

In [ ]:
frame = pd.read_csv('/content/Mcdonalds.csv', usecols=['Item', 'Category', 'Serving Size', 'Calories', 'TotalFat'])
frame.head()

    Category                              Item  ... Calories  TotalFat
0  Breakfast                      Egg McMuffin  ...      300      13.0
1  Breakfast                 Egg White Delight  ...      250       8.0
2  Breakfast                  Sausage McMuffin  ...      370      23.0
3  Breakfast         Sausage McMuffin with Egg  ...      450      28.0
4  Breakfast  Sausage McMuffin with Egg Whites  ...      400      23.0

[5 rows x 5 columns]

In [ ]:
frame['Calories'].rank().head()

0    115.0
1     82.5
2    146.0
3    178.5
4    156.0
Name: Calories, dtype: float64

In [ ]:
frame['CaloriesRank'] = frame['Calories'].rank()
frame.head()

    Category                              Item  ... TotalFat  CaloriesRank
0  Breakfast                      Egg McMuffin  ...     13.0         115.0
1  Breakfast                 Egg White Delight  ...      8.0          82.5
2  Breakfast                  Sausage McMuffin  ...     23.0         146.0
3  Breakfast         Sausage McMuffin with Egg  ...     28.0         178.5
4  Breakfast  Sausage McMuffin with Egg Whites  ...     23.0         156.0

[5 rows x 6 columns]

In [ ]:
frame.sort_values(by = 'Calories').head(20)

           Category                              Item  ... TotalFat  CaloriesRank
125       Beverages            Diet Dr Pepper (Child)  ...      0.0           8.5
138    Coffee & Tea                 Iced Tea (Medium)  ...      0.0           8.5
137    Coffee & Tea                  Iced Tea (Small)  ...      0.0           8.5
136       Beverages               Dasani Water Bottle  ...      0.0           8.5
145    Coffee & Tea                    Coffee (Small)  ...      0.0           8.5
147    Coffee & Tea                    Coffee (Large)  ...      0.0           8.5
124       Beverages            Diet Dr Pepper (Large)  ...      0.0           8.5
139    Coffee & Tea                  Iced Tea (Large)  ...      0.0           8.5
122       Beverages            Diet Dr Pepper (Small)  ...      0.0           8.5
123       Beverages           Diet Dr Pepper (Medium)  ...      0.0           8.5
117       Beverages                 Diet Coke (Child)  ...      0.0           8.5
116       Beverages                 Diet Coke (Large)  ...      0.0           8.5
115       Beverages                Diet Coke (Medium)  ...      0.0           8.5
114       Beverages                 Diet Coke (Small)  ...      0.0           8.5
146    Coffee & Tea                   Coffee (Medium)  ...      0.0           8.5
140    Coffee & Tea                  Iced Tea (Child)  ...      0.0           8.5
101  Snacks & Sides                      Apple Slices  ...      0.0          17.0
100  Snacks & Sides                        Side Salad  ...      0.0          18.0
106        Desserts               Kids Ice Cream Cone  ...      1.5          19.0
132       Beverages  Minute Maid 100% Apple Juice Box  ...      0.0          20.5

[20 rows x 6 columns]

In [ ]:
frame['CaloriesRank'] = frame['Calories'].rank(ascending=False)
frame.sort_values(by='Calories',ascending=False).head(20)

               Category  ... CaloriesRank
82       Chicken & Fish  ...          1.0
32            Breakfast  ...          2.0
31            Breakfast  ...          3.0
34            Breakfast  ...          4.0
33            Breakfast  ...          5.0
81       Chicken & Fish  ...          6.0
253  Smoothies & Shakes  ...          7.0
249  Smoothies & Shakes  ...          8.5
246  Smoothies & Shakes  ...          8.5
251  Smoothies & Shakes  ...         10.5
243  Smoothies & Shakes  ...         10.5
258  Smoothies & Shakes  ...         12.0
28            Breakfast  ...         13.0
231        Coffee & Tea  ...         14.0
47          Beef & Pork  ...         15.5
63       Chicken & Fish  ...         15.5
27            Breakfast  ...         17.0
51          Beef & Pork  ...         18.0
248  Smoothies & Shakes  ...         19.0
30            Breakfast  ...         21.0

[20 rows x 6 columns]

In [ ]:
frame.sort_values(by='Calories',ascending=False,inplace=True)
frame.head(3)

          Category  ... CaloriesRank
82  Chicken & Fish  ...          1.0
32       Breakfast  ...          2.0
31       Breakfast  ...          3.0

[3 rows x 6 columns]

In [ ]:
frame.nlargest(n=3,columns='Calories')

          Category  ... CaloriesRank
82  Chicken & Fish  ...          1.0
32       Breakfast  ...          2.0
31       Breakfast  ...          3.0

[3 rows x 6 columns]

In [ ]:
frame.tail(3)

         Category                Item  ... TotalFat  CaloriesRank
115     Beverages  Diet Coke (Medium)  ...      0.0         252.5
114     Beverages   Diet Coke (Small)  ...      0.0         252.5
146  Coffee & Tea     Coffee (Medium)  ...      0.0         252.5

[3 rows x 6 columns]

In [ ]:
frame.nsmallest(n=3,columns='Calories')

         Category              Item  ... TotalFat  CaloriesRank
145  Coffee & Tea    Coffee (Small)  ...      0.0         252.5
140  Coffee & Tea  Iced Tea (Child)  ...      0.0         252.5
139  Coffee & Tea  Iced Tea (Large)  ...      0.0         252.5

[3 rows x 6 columns]