In [ ]:
import pandas as pd
import numpy as np

In [ ]:
incidents = pd.read_csv('/content/Canadian Railway Crossing Incidents.csv')
incidents.set_index(['Region', 'EventType'],inplace=True)
incidents.sort_index(inplace=True)
incidents.head(10)

                                   Public automated  ...  Farm
Region           EventType                           ...
Alberta          Accidents                        3  ...     0
                 Fatalities                       0  ...     0
                 Serious injuries                 0  ...     0
British Columbia Accidents                        4  ...     0
                 Fatalities                       0  ...     0
                 Serious injuries                 3  ...     0
Manitoba         Accidents                        1  ...     2
                 Fatalities                       0  ...     0
                 Serious injuries                 0  ...     1
New Brunswick    Accidents                        0  ...     0

[10 rows x 4 columns]

In [ ]:
incidents.count()

Public automated    30
Public passive      30
Private             30
Farm                30
dtype: int64

In [ ]:
len(incidents)

30

In [ ]:
incidents.transpose()

Region             Alberta             ... Saskatchewan
EventType        Accidents Fatalities  ...   Fatalities Serious injuries
Public automated         3          0  ...            0                0
Public passive           7          0  ...            0                0
Private                  2          0  ...            0                0
Farm                     0          0  ...            0                0

[4 rows x 30 columns]

In [ ]:
events = incidents.transpose()
events

Region             Alberta             ... Saskatchewan
EventType        Accidents Fatalities  ...   Fatalities Serious injuries
Public automated         3          0  ...            0                0
Public passive           7          0  ...            0                0
Private                  2          0  ...            0                0
Farm                     0          0  ...            0                0

[4 rows x 30 columns]

In [ ]:
events.loc['Private']

Region                 EventType
Alberta                Accidents           2
                       Fatalities          0
                       Serious injuries    2
British Columbia       Accidents           0
                       Fatalities          0
                       Serious injuries    0
Manitoba               Accidents           0
                       Fatalities          0
                       Serious injuries    0
New Brunswick          Accidents           0
                       Fatalities          0
                       Serious injuries    0
Newfoundland           Accidents           0
                       Fatalities          0
                       Serious injuries    0
Northwest Territories  Accidents           0
                       Fatalities          0
                       Serious injuries    0
Nova Scotia            Accidents           0
                       Fatalities          0
                       Serious injuries    0
Ontario                Accidents           2
                       Fatalities          0
                       Serious injuries    0
Quebec                 Accidents           1
                       Fatalities          0
                       Serious injuries    0
Saskatchewan           Accidents           0
                       Fatalities          0
                       Serious injuries    0
Name: Private, dtype: int64

In [ ]:
events.loc['Public passive',('Manitoba','Accidents')]

3

In [ ]:
events.iloc[0,5]

3

In [ ]:
events.transpose().head()

                                   Public automated  ...  Farm
Region           EventType                           ...
Alberta          Accidents                        3  ...     0
                 Fatalities                       0  ...     0
                 Serious injuries                 0  ...     0
British Columbia Accidents                        4  ...     0
                 Fatalities                       0  ...     0

[5 rows x 4 columns]