In [ ]:
import pandas as pd
import numpy as np

In [ ]:
products = pd.read_csv('/content/WA_Sales_Products_2012-14.csv')
products.head()

  Retailer country Order method type  ... Quantity Gross margin
0    United States               Fax  ...      489     0.347548
1    United States               Fax  ...      252     0.474274
2    United States               Fax  ...      147     0.352772
3    United States               Fax  ...      303     0.282938
4    United States               Fax  ...     1415     0.291450

[5 rows x 11 columns]

In [ ]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88475 entries, 0 to 88474
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Retailer country   88475 non-null  object
 1   Order method type  88475 non-null  object
 2   Retailer type      88475 non-null  object
 3   Product line       88475 non-null  object
 4   Product type       88475 non-null  object
 5   Product            88475 non-null  object
 6   Year               88475 non-null  int64
 7   Quarter            88475 non-null  object
 8   Revenue            88475 non-null  float64
 9   Quantity           88475 non-null  int64
 10  Gross margin       87894 non-null  float64
dtypes: float64(2), int64(2), object(7)
memory usage: 7.4+ MB

In [ ]:
products.describe()

               Year       Revenue      Quantity  Gross margin
count  88475.000000  8.847500e+04  88475.000000  87894.000000
mean    2012.855281  4.263829e+04    780.586166      0.449718
std        0.778342  6.578402e+04   1541.645422      0.123642
min     2012.000000  0.000000e+00      1.000000    -12.853678
25%     2012.000000  8.184360e+03    131.000000      0.369880
50%     2013.000000  2.102628e+04    333.000000      0.450634
75%     2013.000000  5.039060e+04    816.000000      0.520130
max     2014.000000  1.635688e+06  67875.000000      0.770476

In [ ]:
products['Retailer country'].value_counts()

United States     7482
Canada            5923
France            5779
Germany           5397
Japan             5359
United Kingdom    5102
Netherlands       4199
Switzerland       4103
Italy             4018
Austria           3862
Mexico            3845
Belgium           3710
Australia         3665
China             3652
Spain             3557
Singapore         3443
Finland           3409
Korea             3399
Brazil            3288
Sweden            2925
Denmark           2358
Name: Retailer country, dtype: int64

In [ ]:
products['Retailer country'].nunique()

21

In [ ]:
countries = products['Retailer country'].unique()
countries

array(['United States', 'Canada', 'Mexico', 'Brazil', 'Japan',
       'Singapore', 'Korea', 'China', 'Australia', 'Netherlands',
       'Sweden', 'Denmark', 'Finland', 'France', 'Germany', 'Switzerland',
       'United Kingdom', 'Belgium', 'Austria', 'Italy', 'Spain'],
      dtype=object)

Tworzę zmienną, która będzie przechowywała grupy razem z danymi tych grup

In [ ]:
myOwnGroups = {}

In [ ]:
for country in countries:
  myOwnSubDataFrame = products.where(products['Retailer country'] == country).dropna()
  myOwnGroups[country] = myOwnSubDataFrame

In [ ]:
myOwnGroups

{'Australia':       Retailer country Order method type  ... Quantity Gross margin
 3735         Australia         Telephone  ...     53.0     0.509564
 3736         Australia         Telephone  ...     70.0     0.507874
 3737         Australia         Telephone  ...    158.0     0.284152
 3738         Australia         Telephone  ...    255.0     0.413692
 3739         Australia         Telephone  ...     46.0     0.437513
 ...                ...               ...  ...      ...          ...
 85862        Australia       Sales visit  ...    138.0     0.509564
 85863        Australia       Sales visit  ...     91.0     0.496579
 85864        Australia       Sales visit  ...     42.0     0.531494
 85865        Australia       Sales visit  ...   1164.0     0.369880
 85866        Australia       Sales visit  ...    169.0     0.511327

 [3639 rows x 11 columns],
 'Austria':       Retailer country Order method type  ... Quantity Gross margin
 7588           Austria         Telephone  ...    137.0     0.373695
 7589           Austria         Telephone  ...     75.0     0.573601
 7590           Austria         Telephone  ...     34.0     0.524498
 7591           Austria         Telephone  ...     11.0     0.569964
 7592           Austria         Telephone  ...    138.0     0.280691
 ...                ...               ...  ...      ...          ...
 88078          Austria               Web  ...    152.0     0.511327
 88079          Austria               Web  ...    164.0     0.523310
 88080          Austria               Web  ...    995.0     0.484462
 88081          Austria               Web  ...     96.0     0.617452
 88082          Austria               Web  ...   2194.0     0.524254

 [3823 rows x 11 columns],
 'Belgium':       Retailer country Order method type  ... Quantity Gross margin
 7270           Belgium               Web  ...     57.0     0.509564
 7271           Belgium               Web  ...     68.0     0.496579
 7272           Belgium               Web  ...     96.0     0.458979
 7273           Belgium               Web  ...     87.0     0.448898
 7274           Belgium               Web  ...     44.0     0.571075
 ...                ...               ...  ...      ...          ...
 87864          Belgium               Web  ...    219.0     0.536567
 87865          Belgium               Web  ...    131.0     0.273312
 87866          Belgium               Web  ...    104.0     0.457647
 87867          Belgium               Web  ...     20.0     0.533432
 87868          Belgium               Web  ...     93.0     0.350754

 [3687 rows x 11 columns],
 'Brazil':       Retailer country Order method type  ... Quantity Gross margin
 1833            Brazil               Web  ...    219.0     0.419206
 1834            Brazil               Web  ...     43.0     0.478828
 1835            Brazil               Web  ...    198.0     0.388419
 1836            Brazil               Web  ...     93.0     0.458950
 1837            Brazil               Web  ...     60.0     0.444223
 ...                ...               ...  ...      ...          ...
 84734           Brazil               Web  ...    146.0     0.511327
 84735           Brazil               Web  ...    137.0     0.523310
 84736           Brazil               Web  ...    828.0     0.484462
 84737           Brazil               Web  ...     90.0     0.617452
 84738           Brazil               Web  ...   1505.0     0.524254

 [3273 rows x 11 columns],
 'Canada':       Retailer country Order method type  ... Quantity Gross margin
 864             Canada               Fax  ...    165.0     0.418630
 865             Canada               Fax  ...    114.0     0.450544
 866             Canada               Fax  ...     17.0     0.473455
 867             Canada               Fax  ...    271.0     0.455317
 868             Canada               Fax  ...    621.0     0.340707
 ...                ...               ...  ...      ...          ...
 84363           Canada               Web  ...   1735.0     0.385281
 84364           Canada               Web  ...    218.0     0.523310
 84365           Canada               Web  ...   1155.0     0.479485
 84366           Canada               Web  ...    116.0     0.617452
 84367           Canada               Web  ...   2566.0     0.524254

 [5904 rows x 11 columns],
 'China':       Retailer country Order method type  ... Quantity Gross margin
 3403             China               Fax  ...    214.0     0.315153
 3404             China               Fax  ...    115.0     0.445356
 3405             China               Fax  ...    290.0     0.501355
 3406             China               Fax  ...    214.0     0.535775
 3407             China               Fax  ...   1568.0     0.506984
 ...                ...               ...  ...      ...          ...
 85667            China               Web  ...    483.0     0.667143
 85668            China               Web  ...    325.0     0.610000
 85669            China               Web  ...    510.0     0.637652
 85670            China               Web  ...   1009.0     0.622449
 85671            China               Web  ...     68.0     0.528333

 [3639 rows x 11 columns],
 'Denmark':       Retailer country Order method type  ... Quantity Gross margin
 4695           Denmark               Web  ...     34.0     0.418630
 4696           Denmark               Web  ...     19.0     0.474727
 4697           Denmark               Web  ...     29.0     0.471715
 4698           Denmark               Web  ...     92.0     0.391537
 4699           Denmark               Web  ...     81.0     0.445985
 ...                ...               ...  ...      ...          ...
 86355          Denmark               Web  ...     69.0     0.416471
 86356          Denmark               Web  ...    177.0     0.468593
 86357          Denmark               Web  ...    101.0     0.356765
 86358          Denmark               Web  ...    198.0     0.463847
 86359          Denmark               Web  ...     52.0     0.533432

 [2348 rows x 11 columns],
 'Finland':       Retailer country Order method type  ... Quantity Gross margin
 4913           Finland               Web  ...   2586.0     0.526656
 4914           Finland               Web  ...   1205.0     0.496009
 4915           Finland               Web  ...    880.0     0.310091
 4916           Finland               Web  ...    794.0     0.336810
 4917           Finland               Web  ...   9282.0     0.496847
 ...                ...               ...  ...      ...          ...
 86546          Finland               Web  ...    283.0     0.523310
 86547          Finland               Web  ...   1231.0     0.670543
 86548          Finland               Web  ...   1203.0     0.479485
 86549          Finland               Web  ...    122.0     0.617452
 86550          Finland               Web  ...   2683.0     0.524254

 [3393 rows x 11 columns],
 'France':       Retailer country Order method type  ... Quantity Gross margin
 5205            France               Fax  ...     39.0     0.445356
 5206            France               Fax  ...     47.0     0.449550
 5207            France               Fax  ...    135.0     0.459332
 5208            France               Fax  ...   8136.0     0.465823
 5209            France               Fax  ...   1081.0     0.496009
 ...                ...               ...  ...      ...          ...
 86854           France       Sales visit  ...    200.0     0.511327
 86855           France       Sales visit  ...    198.0     0.523310
 86856           France       Sales visit  ...    834.0     0.484462
 86857           France       Sales visit  ...     85.0     0.617452
 86858           France       Sales visit  ...   1866.0     0.524254

 [5733 rows x 11 columns],
 'Germany':       Retailer country Order method type  ... Quantity Gross margin
 5807           Germany              Mail  ...    402.0     0.336810
 5808           Germany              Mail  ...    235.0     0.347548
 5809           Germany              Mail  ...    458.0     0.460043
 5810           Germany              Mail  ...    520.0     0.281444
 5811           Germany              Mail  ...    158.0     0.282938
 ...                ...               ...  ...      ...          ...
 87161          Germany               Web  ...    132.0     0.511327
 87162          Germany               Web  ...    171.0     0.523310
 87163          Germany               Web  ...    807.0     0.484462
 87164          Germany               Web  ...     82.0     0.617452
 87165          Germany               Web  ...   1804.0     0.524254

 [5356 rows x 11 columns],
 'Italy':       Retailer country Order method type  ... Quantity Gross margin
 7934             Italy               Fax  ...    126.0     0.329056
 7935             Italy               Fax  ...     75.0     0.291657
 7936             Italy               Fax  ...    113.0     0.301264
 7937             Italy               Fax  ...    190.0     0.427688
 7938             Italy               Fax  ...    265.0     0.564981
 ...                ...               ...  ...      ...          ...
 88276            Italy       Sales visit  ...    515.0     0.495267
 88277            Italy       Sales visit  ...    718.0     0.378449
 88278            Italy       Sales visit  ...    414.0     0.330068
 88279            Italy       Sales visit  ...    152.0     0.321989
 88280            Italy       Sales visit  ...    808.0     0.252632

 [3984 rows x 11 columns],
 'Japan':       Retailer country Order method type  ... Quantity Gross margin
 2146             Japan               Fax  ...   7091.0     0.465823
 2147             Japan               Fax  ...    957.0     0.466974
 2148             Japan               Fax  ...    151.0     0.434205
 2149             Japan               Fax  ...    462.0     0.467061
 2150             Japan               Fax  ...    129.0     0.329056
 ...                ...               ...  ...      ...          ...
 85074            Japan       Sales visit  ...    517.0     0.308878
 85075            Japan       Sales visit  ...    156.0     0.495376
 85076            Japan       Sales visit  ...   1461.0     0.385281
 85077            Japan       Sales visit  ...    186.0     0.511327
 85078            Japan       Sales visit  ...   2252.0     0.524254

 [5308 rows x 11 columns],
 'Korea':       Retailer country Order method type  ... Quantity Gross margin
 3074             Korea         Telephone  ...   1030.0     0.449709
 3075             Korea         Telephone  ...    565.0     0.347548
 3076             Korea         Telephone  ...    839.0     0.260994
 3077             Korea         Telephone  ...    769.0     0.291450
 3078             Korea         Telephone  ...    381.0     0.388535
 ...                ...               ...  ...      ...          ...
 85443            Korea               Web  ...    282.0     0.523310
 85444            Korea               Web  ...   1483.0     0.479485
 85445            Korea               Web  ...    151.0     0.617452
 85446            Korea               Web  ...   3308.0     0.524254
 85447            Korea       Sales visit  ...    382.0     0.540000

 [3373 rows x 11 columns],
 'Mexico':       Retailer country Order method type  ... Quantity Gross margin
 1468            Mexico               Web  ...     21.0     0.474727
 1469            Mexico               Web  ...     34.0     0.478828
 1470            Mexico               Web  ...     26.0     0.451702
 1471            Mexico               Web  ...     17.0     0.444782
 1472            Mexico               Web  ...    126.0     0.340209
 ...                ...               ...  ...      ...          ...
 84551           Mexico               Web  ...   2022.0     0.385281
 84552           Mexico               Web  ...    245.0     0.511327
 84553           Mexico               Web  ...    265.0     0.523310
 84554           Mexico               Web  ...   1437.0     0.479485
 84555           Mexico               Web  ...   2762.0     0.524254

 [3818 rows x 11 columns],
 'Netherlands':       Retailer country Order method type  ... Quantity Gross margin
 4072       Netherlands               Fax  ...   1187.0     0.760563
 4073       Netherlands               Fax  ...    297.0     0.347548
 4074       Netherlands               Fax  ...    556.0     0.260994
 4075       Netherlands               Fax  ...    348.0     0.474274
 4076       Netherlands               Fax  ...   1630.0     0.494949
 ...                ...               ...  ...      ...          ...
 86090      Netherlands               Web  ...    243.0     0.511327
 86091      Netherlands               Web  ...    217.0     0.523310
 86092      Netherlands               Web  ...   1131.0     0.479485
 86093      Netherlands               Web  ...    114.0     0.617452
 86094      Netherlands               Web  ...   2815.0     0.524254

 [4168 rows x 11 columns],
 'Singapore':       Retailer country Order method type  ... Quantity Gross margin
 2750         Singapore               Fax  ...    944.0     0.336810
 2751         Singapore               Fax  ...    378.0     0.529480
 2752         Singapore               Fax  ...    429.0     0.273356
 2753         Singapore               Fax  ...    250.0     0.316417
 2754         Singapore               Fax  ...    103.0     0.361866
 ...                ...               ...  ...      ...          ...
 85255        Singapore               Web  ...    337.0     0.533432
 85256        Singapore               Web  ...    243.0     0.443353
 85257        Singapore               Web  ...    222.0     0.483432
 85258        Singapore               Web  ...    294.0     0.371835
 85259        Singapore               Web  ...     28.0     0.358715

 [3420 rows x 11 columns],
 'Spain':       Retailer country Order method type  ... Quantity Gross margin
 8310             Spain               Fax  ...   1926.0     0.537125
 8311             Spain               Fax  ...    834.0     0.763231
 8312             Spain               Fax  ...    231.0     0.376902
 8313             Spain               Fax  ...     51.0     0.373695
 8314             Spain               Fax  ...     22.0     0.577135
 ...                ...               ...  ...      ...          ...
 88470            Spain       Sales visit  ...    171.0     0.299114
 88471            Spain       Sales visit  ...    191.0     0.446287
 88472            Spain       Sales visit  ...    236.0     0.569420
 88473            Spain       Sales visit  ...   1470.0     0.491667
 88474            Spain       Sales visit  ...   1176.0     0.387895

 [3537 rows x 11 columns],
 'Sweden':       Retailer country Order method type  ... Quantity Gross margin
 4453            Sweden            E-mail  ...    965.0     0.601404
 4454            Sweden            E-mail  ...    150.0     0.282938
 4455            Sweden            E-mail  ...    344.0     0.291450
 4456            Sweden            E-mail  ...    144.0     0.398146
 4457            Sweden            E-mail  ...    151.0     0.335607
 ...                ...               ...  ...      ...          ...
 86258           Sweden       Sales visit  ...     37.0     0.448706
 86259           Sweden       Sales visit  ...    242.0     0.366086
 86260           Sweden       Sales visit  ...    246.0     0.637652
 86261           Sweden       Sales visit  ...    116.0     0.495376
 86262           Sweden       Sales visit  ...   1194.0     0.524254

 [2904 rows x 11 columns],
 'Switzerland':       Retailer country Order method type  ... Quantity Gross margin
 6318       Switzerland               Fax  ...     25.0     0.473455
 6319       Switzerland               Fax  ...     30.0     0.471715
 6320       Switzerland               Fax  ...    126.0     0.391537
 6321       Switzerland               Fax  ...     84.0     0.448412
 6322       Switzerland               Fax  ...     20.0     0.444782
 ...                ...               ...  ...      ...          ...
 87385      Switzerland               Web  ...   1292.0     0.385281
 87386      Switzerland               Web  ...    166.0     0.523310
 87387      Switzerland               Web  ...    712.0     0.484462
 87388      Switzerland               Web  ...     72.0     0.617452
 87389      Switzerland               Web  ...   1572.0     0.524254

 [4069 rows x 11 columns],
 'United Kingdom':       Retailer country Order method type  ... Quantity Gross margin
 6696    United Kingdom               Fax  ...    570.0     0.419461
 6697    United Kingdom               Fax  ...    170.0     0.474224
 6698    United Kingdom               Fax  ...    124.0     0.448247
 6699    United Kingdom               Fax  ...     51.0     0.466953
 6700    United Kingdom               Fax  ...    132.0     0.417333
 ...                ...               ...  ...      ...          ...
 87672   United Kingdom       Sales visit  ...     18.0     0.597248
 87673   United Kingdom       Sales visit  ...   2771.0     0.294893
 87674   United Kingdom       Sales visit  ...    227.0     0.296456
 87675   United Kingdom       Sales visit  ...    168.0     0.443353
 87676   United Kingdom       Sales visit  ...    132.0     0.483432

 [5069 rows x 11 columns],
 'United States':       Retailer country Order method type  ... Quantity Gross margin
 0        United States               Fax  ...    489.0     0.347548
 1        United States               Fax  ...    252.0     0.474274
 2        United States               Fax  ...    147.0     0.352772
 3        United States               Fax  ...    303.0     0.282938
 4        United States               Fax  ...   1415.0     0.291450
 ...                ...               ...  ...      ...          ...
 84049    United States       Sales visit  ...    218.0     0.483112
 84050    United States       Sales visit  ...    905.0     0.494896
 84051    United States       Sales visit  ...     72.0     0.547336
 84052    United States       Sales visit  ...     45.0     0.485414
 84053    United States       Sales visit  ...    833.0     0.288314

 [7449 rows x 11 columns]}

In [ ]:
myOwnGroups['Belgium'].head()

     Retailer country Order method type  ... Quantity Gross margin
7270          Belgium               Web  ...     57.0     0.509564
7271          Belgium               Web  ...     68.0     0.496579
7272          Belgium               Web  ...     96.0     0.458979
7273          Belgium               Web  ...     87.0     0.448898
7274          Belgium               Web  ...     44.0     0.571075

[5 rows x 11 columns]

In [ ]:
myOwnGroups['Mexico'].describe()

              Year        Revenue      Quantity  Gross margin
count  3818.000000    3818.000000   3818.000000   3818.000000
mean   2012.846255   36503.301472    665.858565      0.448840
std       0.769600   49339.336611   1152.229229      0.110507
min    2012.000000     138.000000      1.000000     -0.179180
25%    2012.000000    8405.235000    132.000000      0.368511
50%    2013.000000   19554.070000    329.000000      0.449550
75%    2013.000000   43455.885000    753.500000      0.517297
max    2014.000000  464070.900000  19214.000000      0.770476